name: Linting and Typechecking

on:
  push:
    branches: ['main', 'develop']

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

   - name: Clean Install dependencies
        run: pnpm run ci

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck
