name: Linting and Typechecking

on:
  push:
    branches: ['main', 'develop']

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Clean Install dependencies
        run: pnpm run ci

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck
